version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://suryatech128:surya@authsystem.vgpfu.mongodb.net/auth?retryWrites=true&w=majority&appName=authsystem
      - PORT=5000
      - ACCESS_TOKEN_SECRET=test_access_token_secret
      - REFRESH_TOKEN_SECRET=test_refresh_token_secret
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=suryatech128@gmail.com
      - EMAIL_PASS=uetk ywbo bljk bubc
      - EMAIL_FROM=suryatech128@gmail.com
      - FRONTEND_URL=http://localhost:3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
      - GOOGLE_CLIENT_ID=35998161146-curhb31ut84oluvvagh8re4r41gpoopm.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

